// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  model

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( NovelChapters ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* NovelChapters ) UnmarshalJSON([]byte) error { return nil }
func ( NovelChapters ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NovelChapters ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NovelChapters *NovelChapters
