// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  httpserv

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( NightcErr ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* NightcErr ) UnmarshalJSON([]byte) error { return nil }
func ( NightcErr ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NightcErr ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NightcErr *NightcErr
